version: '3.4'

services:
    mvcmovie:
        depends_on:
            - sql.data
        build:
            context: . 
            dockerfile: MvcMovie/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ConnectionStrings__MvcMovieContext=Data Source=sql.data;Initial Catalog=MvcMovie;User ID=sa;Password=Passw0rd;
        ports:
            - "8080:80"
    sql.data:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - MSSQL_SA_PASSWORD=Passw0rd
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"