version: '3.4'

services:
    mvcmovie:
        depends_on:
            - sql.data
        build:
            context: .
            dockerfile: Dockerfile
    sql.data:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - MSSQL_SA_PASSWORD=Pass@word
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"